import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

const Home = () => {
  const { isAuthenticated } = useAuth();

  return (
    <div className="max-w-6xl mx-auto">
      {/* Hero Section */}
      <div className="text-center py-12 sm:py-20">
        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-gray-900 mb-6">
          Personalized Food
          <span className="text-blue-600 block sm:inline sm:ml-3">
            Recommendations
          </span>
        </h1>
        <p className="text-lg sm:text-xl text-gray-600 mb-8 max-w-3xl mx-auto leading-relaxed">
          Get AI-powered meal recommendations tailored to your health goals, dietary preferences, 
          and medical conditions. Whether you're a patient managing your nutrition or a doctor 
          overseeing patient care, we've got you covered.
        </p>
        
        <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
          {isAuthenticated() ? (
            <Link
              to="/dashboard"
              className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-8 rounded-lg transition-colors shadow-lg hover:shadow-xl"
            >
              Go to Dashboard
            </Link>
          ) : (
            <>
              <Link
                to="/register"
                className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-8 rounded-lg transition-colors shadow-lg hover:shadow-xl"
              >
                Get Started
              </Link>
              <Link
                to="/login"
                className="bg-gray-100 hover:bg-gray-200 text-gray-800 font-semibold py-3 px-8 rounded-lg transition-colors border border-gray-300"
              >
                Sign In
              </Link>
            </>
          )}
        </div>
      </div>

      {/* Features Section */}
      <div className="py-16 border-t border-gray-200">
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
            Why Choose Our System?
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Advanced AI technology meets personalized healthcare for optimal nutrition planning
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {/* Feature 1 */}
          <div className="bg-white rounded-xl shadow-md p-6 hover:shadow-lg transition-shadow">
            <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
              <span className="text-2xl">🤖</span>
            </div>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">
              AI-Powered Recommendations
            </h3>
            <p className="text-gray-600">
              Get personalized meal plans generated by advanced AI that considers your health profile, 
              dietary preferences, and medical conditions.
            </p>
          </div>

          {/* Feature 2 */}
          <div className="bg-white rounded-xl shadow-md p-6 hover:shadow-lg transition-shadow">
            <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
              <span className="text-2xl">👥</span>
            </div>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">
              Dual Role Support
            </h3>
            <p className="text-gray-600">
              Designed for both patients managing their own nutrition and healthcare providers 
              overseeing multiple patient meal plans.
            </p>
          </div>

          {/* Feature 3 */}
          <div className="bg-white rounded-xl shadow-md p-6 hover:shadow-lg transition-shadow">
            <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-4">
              <span className="text-2xl">📊</span>
            </div>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">
              Detailed Nutrition Tracking
            </h3>
            <p className="text-gray-600">
              Complete nutritional breakdown for every meal including calories, protein, 
              carbs, fat, and fiber content.
            </p>
          </div>

          {/* Feature 4 */}
          <div className="bg-white rounded-xl shadow-md p-6 hover:shadow-lg transition-shadow">
            <div className="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center mb-4">
              <span className="text-2xl">🎯</span>
            </div>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">
              Goal-Oriented Planning
            </h3>
            <p className="text-gray-600">
              Whether it's weight loss, muscle gain, or managing health conditions, 
              get meal plans aligned with your specific goals.
            </p>
          </div>

          {/* Feature 5 */}
          <div className="bg-white rounded-xl shadow-md p-6 hover:shadow-lg transition-shadow">
            <div className="w-12 h-12 bg-red-100 rounded-lg flex items-center justify-center mb-4">
              <span className="text-2xl">🚫</span>
            </div>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">
              Allergy & Preference Aware
            </h3>
            <p className="text-gray-600">
              Automatically excludes allergens and foods you dislike while respecting 
              your dietary preferences (vegetarian, non-vegetarian, mixed).
            </p>
          </div>

          {/* Feature 6 */}
          <div className="bg-white rounded-xl shadow-md p-6 hover:shadow-lg transition-shadow">
            <div className="w-12 h-12 bg-indigo-100 rounded-lg flex items-center justify-center mb-4">
              <span className="text-2xl">🔒</span>
            </div>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">
              Secure & Private
            </h3>
            <p className="text-gray-600">
              Your health data is protected with industry-standard security measures 
              and role-based access controls.
            </p>
          </div>
        </div>
      </div>

      {/* CTA Section */}
      {!isAuthenticated() && (
        <div className="py-16 text-center bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl mt-16">
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
            Ready to Start Your Journey?
          </h2>
          <p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto">
            Join thousands of users who are already improving their health with personalized nutrition
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link
              to="/register"
              className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-8 rounded-lg transition-colors shadow-lg hover:shadow-xl"
            >
              Create Account
            </Link>
            <Link
              to="/login"
              className="text-blue-600 hover:text-blue-700 font-semibold py-3 px-8 rounded-lg transition-colors"
            >
              Already have an account? Sign in →
            </Link>
          </div>
        </div>
      )}
    </div>
  );
};

export default Home;